# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='motto',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
