# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0003_auto_20160528_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='locality',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='region',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
