# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0004_auto_20161021_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceappearance',
            name='backup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup', to='TBAW.Team'),
        ),
        migrations.AddField(
            model_name='allianceappearance',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='TBAW.Team'),
        ),
        migrations.AddField(
            model_name='allianceappearance',
            name='first_pick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_pick', to='TBAW.Team'),
        ),
        migrations.AddField(
            model_name='allianceappearance',
            name='second_pick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_pick', to='TBAW.Team'),
        ),
    ]
