# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0005_auto_20161021_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='key',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
