# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0006_event_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_address',
            field=models.TextField(null=True),
        ),
    ]
