# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0007_auto_20161024_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
