# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0008_auto_20161024_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
