# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0008_alliance_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='alliances',
            field=models.ManyToManyField(to='TBAW.Alliance'),
        ),
    ]
