# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-06 01:47
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0009_auto_20161024_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='active_years',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
