# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0009_match_alliances'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue')], max_length=4, null=True),
        ),
    ]
