# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-08 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0010_team_active_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='active_years',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=[], max_length=255, size=None),
        ),
    ]
