# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-08 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0011_auto_20161208_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='active_years',
            field=django_mysql.models.SetCharField(models.IntegerField(), default=set(), max_length=255, size=None),
        ),
    ]
