# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0012_auto_20160531_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='time_string',
        ),
    ]
