# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0013_remove_match_time_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='foul_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='total_autonomous_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='total_foul_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='total_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='total_teleop_points',
            field=models.IntegerField(null=True),
        ),
    ]
