# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0014_auto_20160531_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='foul_count',
            new_name='red_total_teleop_points',
        ),
        migrations.RemoveField(
            model_name='match',
            name='total_autonomous_points',
        ),
        migrations.RemoveField(
            model_name='match',
            name='total_foul_points',
        ),
        migrations.RemoveField(
            model_name='match',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='total_teleop_points',
        ),
        migrations.AddField(
            model_name='match',
            name='blue_foul_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_total_autonomous_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_total_foul_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_total_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_total_teleop_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red_foul_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red_total_autonomous_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red_total_foul_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='red_total_score',
            field=models.IntegerField(null=True),
        ),
    ]
