# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0016_auto_20160601_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='TBAW.Alliance'),
        ),
    ]
