# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('TBAW', '0017_auto_20160601_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_total_score', models.SmallIntegerField()),
                ('red_auton_score', models.SmallIntegerField()),
                ('red_teleop_score', models.SmallIntegerField()),
                ('red_foul_score', models.SmallIntegerField()),
                ('red_foul_count', models.SmallIntegerField(default=-1)),
                ('blue_total_score', models.SmallIntegerField()),
                ('blue_auton_score', models.SmallIntegerField()),
                ('blue_teleop_score', models.SmallIntegerField()),
                ('blue_foul_score', models.SmallIntegerField()),
                ('blue_foul_count', models.SmallIntegerField(default=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoringModel2014',
            fields=[
                ('scoringmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TBAW.ScoringModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('TBAW.scoringmodel',),
        ),
        migrations.CreateModel(
            name='ScoringModel2015',
            fields=[
                ('scoringmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TBAW.ScoringModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('TBAW.scoringmodel',),
        ),
        migrations.CreateModel(
            name='ScoringModel2016',
            fields=[
                ('scoringmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TBAW.ScoringModel')),
                ('defense1', models.CharField(max_length=20)),
                ('defense_1_crossed_count', models.SmallIntegerField()),
                ('defense2', models.CharField(max_length=20)),
                ('defense_2_cross_count', models.SmallIntegerField()),
                ('defense3', models.CharField(max_length=20)),
                ('defense_3_crossed_count', models.SmallIntegerField()),
                ('defense4', models.CharField(max_length=20)),
                ('defense_4_cross_count', models.SmallIntegerField()),
                ('red_breach_points', models.SmallIntegerField()),
                ('red_capture_points', models.SmallIntegerField()),
                ('blue_breach_points', models.SmallIntegerField()),
                ('blue_capture_points', models.SmallIntegerField()),
                ('red_scale_points', models.SmallIntegerField()),
                ('blue_scale_points', models.SmallIntegerField()),
                ('red_auton_boulders_low', models.SmallIntegerField()),
                ('red_auton_boulders_high', models.SmallIntegerField()),
                ('red_auton_boulders_points', models.SmallIntegerField()),
                ('red_teleop_boulders_points', models.SmallIntegerField()),
                ('blue_auton_boulders_low', models.SmallIntegerField()),
                ('blue_auton_boulders_high', models.SmallIntegerField()),
                ('blue_auton_boulders_points', models.SmallIntegerField()),
                ('blue_teleop_boulders_points', models.SmallIntegerField()),
                ('red_auton_crossing_points', models.SmallIntegerField()),
                ('red_auton_reach_points', models.SmallIntegerField()),
                ('red_teleop_crossing_points', models.SmallIntegerField()),
                ('blue_auton_crossing_points', models.SmallIntegerField()),
                ('blue_auton_reach_points', models.SmallIntegerField()),
                ('blue_teleop_crossing_points', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('TBAW.scoringmodel',),
        ),
        migrations.AddField(
            model_name='scoringmodel',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_tbaw.scoringmodel_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='match',
            name='scoring_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBAW.ScoringModel'),
        ),
    ]
