# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0019_auto_20160602_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringmodel',
            name='json_data',
            field=models.TextField(default=''),
        ),
    ]
