# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0020_scoringmodel_json_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringmodel2016',
            name='defense1',
        ),
        migrations.RemoveField(
            model_name='scoringmodel2016',
            name='defense2',
        ),
        migrations.RemoveField(
            model_name='scoringmodel2016',
            name='defense3',
        ),
        migrations.RemoveField(
            model_name='scoringmodel2016',
            name='defense4',
        ),
        migrations.RemoveField(
            model_name='scoringmodel2016',
            name='defense_1_crossed_count',
        ),
        migrations.RemoveField(
            model_name='scoringmodel2016',
            name='defense_2_cross_count',
        ),
        migrations.RemoveField(
            model_name='scoringmodel2016',
            name='defense_3_crossed_count',
        ),
        migrations.RemoveField(
            model_name='scoringmodel2016',
            name='defense_4_cross_count',
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_defense1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_defense2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_defense3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_defense4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_defense_1_crossed_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_defense_2_cross_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_defense_3_crossed_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_defense_4_cross_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_defense1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_defense2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_defense3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_defense4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_defense_1_crossed_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_defense_2_cross_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_defense_3_crossed_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_defense_4_cross_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
