# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0021_auto_20160602_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_low_bar_cross_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_low_bar_cross_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
