# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0025_auto_20160602_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_adjust_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_auton_boulders_high',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_auton_boulders_low',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_auton_boulders_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_auton_crossing_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_auton_reach_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_breach_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_capture_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_defense1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_defense2',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_defense3',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_defense4',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_defense_1_cross_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_defense_2_cross_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_defense_3_cross_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_defense_4_cross_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_defenses_breached',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_low_bar_cross_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_robot1_auto',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_robot2_auto',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_robot3_auto',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_scale_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_teleop_boulders_high',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_teleop_boulders_low',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_teleop_boulders_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_teleop_challenge_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_teleop_crossing_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_tower_captured',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_tower_end_strength',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_tower_faceA',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_tower_faceB',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_tower_faceC',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_adjust_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_auton_boulders_high',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_auton_boulders_low',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_auton_boulders_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_auton_crossing_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_auton_reach_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_breach_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_capture_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_defense1',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_defense2',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_defense3',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_defense4',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_defense_1_cross_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_defense_2_cross_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_defense_3_cross_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_defense_4_cross_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_defenses_breached',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_low_bar_cross_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_robot1_auto',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_robot2_auto',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_robot3_auto',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_scale_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_teleop_boulders_high',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_teleop_boulders_low',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_teleop_boulders_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_teleop_challenge_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_teleop_crossing_points',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_tower_captured',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_tower_end_strength',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_tower_faceA',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_tower_faceB',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_tower_faceC',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
