# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0026_auto_20160602_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringmodel',
            name='blue_auton_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel',
            name='blue_foul_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel',
            name='blue_foul_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel',
            name='blue_tech_foul_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel',
            name='blue_teleop_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel',
            name='blue_total_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel',
            name='json_data',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel',
            name='red_auton_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel',
            name='red_foul_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel',
            name='red_foul_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel',
            name='red_tech_foul_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel',
            name='red_teleop_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel',
            name='red_total_score',
            field=models.SmallIntegerField(null=True),
        ),
    ]
