# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0027_auto_20160602_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoringmodel2016',
            old_name='blue_defense_1_cross_count',
            new_name='blue_defense1_cross_count',
        ),
        migrations.RenameField(
            model_name='scoringmodel2016',
            old_name='blue_defense_2_cross_count',
            new_name='blue_defense2_cross_count',
        ),
        migrations.RenameField(
            model_name='scoringmodel2016',
            old_name='blue_defense_3_cross_count',
            new_name='blue_defense3_cross_count',
        ),
        migrations.RenameField(
            model_name='scoringmodel2016',
            old_name='blue_defense_4_cross_count',
            new_name='blue_defense4_cross_count',
        ),
        migrations.RenameField(
            model_name='scoringmodel2016',
            old_name='red_defense_1_cross_count',
            new_name='red_defense1_cross_count',
        ),
        migrations.RenameField(
            model_name='scoringmodel2016',
            old_name='red_defense_2_cross_count',
            new_name='red_defense2_cross_count',
        ),
        migrations.RenameField(
            model_name='scoringmodel2016',
            old_name='red_defense_3_cross_count',
            new_name='red_defense3_cross_count',
        ),
        migrations.RenameField(
            model_name='scoringmodel2016',
            old_name='red_defense_4_cross_count',
            new_name='red_defense4_cross_count',
        ),
    ]
