# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0028_auto_20160603_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='seed',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
