# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('TBAW', '0029_alliance_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(null=True)),
                ('wins', models.PositiveSmallIntegerField(null=True)),
                ('losses', models.PositiveSmallIntegerField(null=True)),
                ('ties', models.PositiveSmallIntegerField(null=True)),
                ('played', models.PositiveSmallIntegerField(null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_tbaw.rankingmodel_set+', to='contenttypes.ContentType')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBAW.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='rankings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBAW.RankingModel'),
        ),
    ]
