# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0030_auto_20160606_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingmodel',
            name='tba_ccwms',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rankingmodel',
            name='tba_dpr',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rankingmodel',
            name='tba_opr',
            field=models.FloatField(null=True),
        ),
    ]
