# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0032_remove_rankingmodel_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingmodel',
            name='rank',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
