# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0034_rankingmodel2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingModel2015',
            fields=[
                ('rankingmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TBAW.RankingModel')),
                ('qual_average', models.FloatField(null=True)),
                ('auton_points', models.PositiveSmallIntegerField(null=True)),
                ('container_points', models.PositiveSmallIntegerField(null=True)),
                ('coopertition_points', models.PositiveSmallIntegerField(null=True)),
                ('litter_points', models.PositiveSmallIntegerField(null=True)),
                ('tote_points', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('TBAW.rankingmodel',),
        ),
    ]
