# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0035_rankingmodel2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rankings',
        ),
        migrations.AddField(
            model_name='rankingmodel',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBAW.Event'),
        ),
    ]
