# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0037_auto_20160607_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBAW.Team'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='key',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
