# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0038_auto_20160607_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='elo_mu',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='team',
            name='elo_sigma',
            field=models.FloatField(default=8.33333),
        ),
    ]
