# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0039_auto_20160607_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
