# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0040_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='elo_sigma',
            field=models.FloatField(default=8.333333333333334),
        ),
    ]
