# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0041_auto_20160607_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='winning_alliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_alliance', to='TBAW.Alliance'),
        ),
    ]
