# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0042_event_winning_alliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
