# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0043_auto_20160611_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceAppearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(null=True)),
                ('alliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBAW.Alliance')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TBAW.Event')),
            ],
        ),
    ]
