# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0044_allianceappearance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allianceappearance',
            old_name='rank',
            new_name='seed',
        ),
    ]
