# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0045_auto_20160611_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alliance',
            name='color',
        ),
        migrations.RemoveField(
            model_name='alliance',
            name='seed',
        ),
    ]
