# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0047_auto_20160614_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
