# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0049_award_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='recipient',
            new_name='recipients',
        ),
    ]
