# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0050_auto_20160614_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='recipients',
        ),
        migrations.AddField(
            model_name='award',
            name='recipients',
            field=models.ManyToManyField(null=True, to='TBAW.Team'),
        ),
    ]
