# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0051_auto_20160614_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='color',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_alliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_alliance', to='TBAW.Alliance'),
        ),
        migrations.AddField(
            model_name='match',
            name='red_alliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_alliance', to='TBAW.Alliance'),
        ),
        migrations.AlterField(
            model_name='award',
            name='recipients',
            field=models.ManyToManyField(to='TBAW.Team'),
        ),
    ]
