# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0052_auto_20160615_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingmodel',
            name='elo_post',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rankingmodel',
            name='elo_pre',
            field=models.FloatField(null=True),
        ),
    ]
