# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0053_auto_20160706_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankingmodel',
            old_name='elo_post',
            new_name='elo_mu_post',
        ),
        migrations.RenameField(
            model_name='rankingmodel',
            old_name='elo_pre',
            new_name='elo_mu_pre',
        ),
        migrations.AddField(
            model_name='rankingmodel',
            name='elo_sigma_post',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rankingmodel',
            name='elo_sigma_pre',
            field=models.FloatField(null=True),
        ),
    ]
