# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0054_auto_20160706_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='elo_mu',
            field=models.FloatField(default=25),
        ),
        migrations.AddField(
            model_name='alliance',
            name='elo_sigma',
            field=models.FloatField(default=8.333333333333334),
        ),
    ]
