# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0055_auto_20160709_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceappearance',
            name='elo_mu_post',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='allianceappearance',
            name='elo_mu_pre',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='allianceappearance',
            name='elo_sigma_post',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='allianceappearance',
            name='elo_sigma_pre',
            field=models.FloatField(null=True),
        ),
    ]
