# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0056_auto_20160712_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringmodel',
            name='json_data',
        ),
    ]
