# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0057_remove_scoringmodel_json_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankingmodel',
            old_name='losses',
            new_name='qual_losses',
        ),
        migrations.RenameField(
            model_name='rankingmodel',
            old_name='ties',
            new_name='qual_ties',
        ),
        migrations.RenameField(
            model_name='rankingmodel',
            old_name='wins',
            new_name='qual_wins',
        ),
    ]
