# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0060_auto_20160718_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
