# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0061_auto_20160720_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
