# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0063_auto_20160720_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingmodel',
            name='qual_losses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='qual_ties',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='qual_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
