# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0064_auto_20160720_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingModel2014',
            fields=[
                ('rankingmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TBAW.RankingModel')),
                ('qual_score', models.PositiveSmallIntegerField(null=True)),
                ('assist_points', models.PositiveSmallIntegerField(null=True)),
                ('truss_catch_points', models.PositiveSmallIntegerField(null=True)),
                ('auton_points', models.PositiveSmallIntegerField(null=True)),
                ('teleop_points', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('TBAW.rankingmodel',),
        ),
        migrations.RemoveField(
            model_name='scoringmodel',
            name='blue_auton_score',
        ),
        migrations.RemoveField(
            model_name='scoringmodel',
            name='blue_foul_count',
        ),
        migrations.RemoveField(
            model_name='scoringmodel',
            name='blue_foul_score',
        ),
        migrations.RemoveField(
            model_name='scoringmodel',
            name='blue_tech_foul_count',
        ),
        migrations.RemoveField(
            model_name='scoringmodel',
            name='blue_teleop_score',
        ),
        migrations.RemoveField(
            model_name='scoringmodel',
            name='red_auton_score',
        ),
        migrations.RemoveField(
            model_name='scoringmodel',
            name='red_foul_count',
        ),
        migrations.RemoveField(
            model_name='scoringmodel',
            name='red_foul_score',
        ),
        migrations.RemoveField(
            model_name='scoringmodel',
            name='red_tech_foul_count',
        ),
        migrations.RemoveField(
            model_name='scoringmodel',
            name='red_teleop_score',
        ),
        migrations.AddField(
            model_name='scoringmodel2015',
            name='blue_auton_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2015',
            name='blue_foul_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2015',
            name='blue_foul_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2015',
            name='blue_teleop_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2015',
            name='red_auton_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2015',
            name='red_foul_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2015',
            name='red_foul_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2015',
            name='red_teleop_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_auton_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_foul_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_foul_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_tech_foul_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='blue_teleop_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_auton_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_foul_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_foul_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_tech_foul_count',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scoringmodel2016',
            name='red_teleop_score',
            field=models.SmallIntegerField(null=True),
        ),
    ]
