# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0065_auto_20160721_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingmodel',
            name='elo_mu_post',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='elo_mu_pre',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='elo_sigma_post',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rankingmodel',
            name='elo_sigma_pre',
            field=models.FloatField(default=0, null=True),
        ),
    ]
