# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0066_auto_20160721_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='active_event_winstreak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='longest_event_winstreak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
