# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-17 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0067_auto_20160908_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingmodel',
            name='total_losses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rankingmodel',
            name='total_ties',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rankingmodel',
            name='total_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
