# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0068_auto_20160917_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_auton_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_foul_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='blue_teleop_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_auton_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_foul_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2016',
            name='red_teleop_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
