# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0069_auto_20160919_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_auton_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_container_count_1',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_container_count_2',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_container_count_3',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_container_count_4',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_container_count_5',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_container_count_6',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_container_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_container_set',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_foul_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_litter_count_container',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_litter_count_landfill',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_litter_count_unprocessed',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_litter_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_robot_set',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_teleop_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_tote_count_far',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_tote_count_near',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_tote_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_tote_set',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='blue_tote_stack',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_auton_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_container_count_1',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_container_count_2',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_container_count_3',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_container_count_4',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_container_count_5',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_container_count_6',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_container_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_container_set',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_foul_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_litter_count_container',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_litter_count_landfill',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_litter_count_unprocessed',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_litter_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_robot_set',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_teleop_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_tote_count_far',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_tote_count_near',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_tote_points',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_tote_set',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoringmodel2015',
            name='red_tote_stack',
            field=models.NullBooleanField(default=False),
        ),
    ]
