# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0070_auto_20160919_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.ManyToManyField(related_name='losses', to='TBAW.Match'),
        ),
        migrations.AddField(
            model_name='team',
            name='ties',
            field=models.ManyToManyField(related_name='ties', to='TBAW.Match'),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.ManyToManyField(related_name='wins', to='TBAW.Match'),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='elo_mu',
            field=models.FloatField(default=1500),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='elo_sigma',
            field=models.FloatField(default=500.0),
        ),
        migrations.AlterField(
            model_name='team',
            name='elo_mu',
            field=models.FloatField(default=1500),
        ),
        migrations.AlterField(
            model_name='team',
            name='elo_sigma',
            field=models.FloatField(default=500.0),
        ),
    ]
