# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0071_auto_20160922_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ties',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
        migrations.AddField(
            model_name='team',
            name='awards_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='blue_banners_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='event_losses_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='event_winrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='event_wins_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='match_losses_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='match_ties_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='match_winrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='match_wins_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
