# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0072_auto_20160922_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='event_losses_count',
            new_name='event_attended_count',
        ),
    ]
