# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0074_auto_20160925_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScoringModel2014',
            new_name='ScoringModelOld',
        ),
    ]
