# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0075_auto_20161019_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringmodelold',
            name='scoringmodel_ptr',
        ),
        migrations.DeleteModel(
            name='ScoringModelOld',
        ),
    ]
