# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-20 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TBAW', '0070_auto_20160919_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('teams', models.ManyToManyField(to='TBAW.Team')),
            ],
        ),
    ]
