# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('TBAW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(default='-ret_field', max_length=50, null=True)),
                ('operator', models.CharField(choices=[('+', '_operator.add'), ('-', '_operator.sub'), ('*', '_operator.mul'), ('/', '_operator.truediv'), ('greatest', 'django.db.models.functions.Greatest'), ('least', 'django.db.models.functions.Least')], default='+', max_length=10)),
                ('description', models.TextField(default='')),
                ('field_1', models.CharField(max_length=50, null=True)),
                ('field_2', models.CharField(max_length=50, null=True)),
                ('field_3', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(choices=[('Alltime', 'Alltime'), ('2016', '2016'), ('2015', '2015')], default='Alltime', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllianceLeaderboard',
            fields=[
                ('leaderboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leaderboard2.Leaderboard')),
                ('alliances', models.ManyToManyField(to='TBAW.Alliance')),
            ],
            options={
                'abstract': False,
            },
            bases=('leaderboard2.leaderboard',),
        ),
        migrations.CreateModel(
            name='RankingLeaderboard',
            fields=[
                ('leaderboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leaderboard2.Leaderboard')),
                ('ranking_models', models.ManyToManyField(to='TBAW.RankingModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('leaderboard2.leaderboard',),
        ),
        migrations.CreateModel(
            name='ScoringLeaderboard2015',
            fields=[
                ('leaderboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leaderboard2.Leaderboard')),
                ('scoring_models', models.ManyToManyField(to='TBAW.ScoringModel2015')),
            ],
            options={
                'abstract': False,
            },
            bases=('leaderboard2.leaderboard',),
        ),
        migrations.CreateModel(
            name='ScoringLeaderboard2016',
            fields=[
                ('leaderboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leaderboard2.Leaderboard')),
                ('scoring_models', models.ManyToManyField(to='TBAW.ScoringModel2016')),
            ],
            options={
                'abstract': False,
            },
            bases=('leaderboard2.leaderboard',),
        ),
        migrations.CreateModel(
            name='TeamLeaderboard',
            fields=[
                ('leaderboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leaderboard2.Leaderboard')),
                ('teams', models.ManyToManyField(to='TBAW.Team')),
            ],
            options={
                'abstract': False,
            },
            bases=('leaderboard2.leaderboard',),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_leaderboard2.leaderboard_set+', to='contenttypes.ContentType'),
        ),
    ]
