# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='category',
            field=models.CharField(choices=[('All Time', 'All Time'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014')], default='All Time', max_length=50),
        ),
    ]
