# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 00:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleaderboard',
            name='field',
            field=models.CharField(default=datetime.datetime(2016, 9, 21, 0, 12, 50, 724772, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
