# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='description',
            new_name='desc',
        ),
    ]
