# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0002_auto_20160920_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='field',
        ),
    ]
