# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0003_auto_20160920_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='rankingleaderboard',
            name='leaderboard_ptr',
        ),
        migrations.RemoveField(
            model_name='rankingleaderboard',
            name='ranking_models',
        ),
        migrations.RemoveField(
            model_name='scoringleaderboard',
            name='leaderboard_ptr',
        ),
        migrations.RemoveField(
            model_name='scoringleaderboard',
            name='scoring_models',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='leaderboard_ptr',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='teams',
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='RankingLeaderboard',
        ),
        migrations.DeleteModel(
            name='ScoringLeaderboard',
        ),
        migrations.DeleteModel(
            name='TeamLeaderboard',
        ),
    ]
