# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0003_auto_20161017_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='category',
            field=models.CharField(choices=[('Alltime', 'Alltime'), ('2016', '2016'), ('2015', '2015')], default='Alltime', max_length=50),
        ),
    ]
