# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('TBAW', '0070_auto_20160919_2121'),
        ('leaderboard2', '0004_auto_20160920_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('field', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RankingLeaderboard',
            fields=[
                ('leaderboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leaderboard2.Leaderboard')),
                ('ranking_models', models.ManyToManyField(to='TBAW.RankingModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('leaderboard2.leaderboard',),
        ),
        migrations.CreateModel(
            name='ScoringLeaderboard',
            fields=[
                ('leaderboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leaderboard2.Leaderboard')),
                ('scoring_models', models.ManyToManyField(to='TBAW.ScoringModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('leaderboard2.leaderboard',),
        ),
        migrations.CreateModel(
            name='TeamLeaderboard',
            fields=[
                ('leaderboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leaderboard2.Leaderboard')),
                ('teams', models.ManyToManyField(to='TBAW.Team')),
            ],
            options={
                'abstract': False,
            },
            bases=('leaderboard2.leaderboard',),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_leaderboard2.leaderboard_set+', to='contenttypes.ContentType'),
        ),
    ]
