# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0070_auto_20160919_2121'),
        ('leaderboard2', '0005_auto_20160920_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceLeaderboard',
            fields=[
                ('leaderboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leaderboard2.Leaderboard')),
                ('alliances', models.ManyToManyField(to='TBAW.Alliance')),
            ],
            options={
                'abstract': False,
            },
            bases=('leaderboard2.leaderboard',),
        ),
    ]
