# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0006_allianceleaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringleaderboard',
            name='extra_field_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoringleaderboard',
            name='extra_field_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoringleaderboard',
            name='extra_field_3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
