# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0007_auto_20161007_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringleaderboard',
            name='year',
            field=models.PositiveSmallIntegerField(default=2016),
            preserve_default=False,
        ),
    ]
