# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0009_auto_20161007_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScoringLeaderboard',
            new_name='ScoringLeaderboard2016',
        ),
        migrations.AlterField(
            model_name='scoringleaderboard2016',
            name='scoring_models',
            field=models.ManyToManyField(to='TBAW.ScoringModel2016'),
        ),
    ]
