# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TBAW', '0074_auto_20160925_2139'),
        ('leaderboard2', '0011_auto_20161007_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringLeaderboard2016',
            fields=[
                ('leaderboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leaderboard2.Leaderboard')),
                ('scoring_models', models.ManyToManyField(to='TBAW.ScoringModel2016')),
            ],
            options={
                'abstract': False,
            },
            bases=('leaderboard2.leaderboard',),
        ),
    ]
