# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0012_scoringleaderboard2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringleaderboard2016',
            name='extra_field_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoringleaderboard2016',
            name='extra_field_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoringleaderboard2016',
            name='extra_field_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='field',
            field=models.CharField(default='ret_field', max_length=50),
        ),
    ]
