# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0013_auto_20161007_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoringleaderboard2016',
            old_name='extra_field_1',
            new_name='field_1',
        ),
        migrations.RenameField(
            model_name='scoringleaderboard2016',
            old_name='extra_field_2',
            new_name='field_2',
        ),
        migrations.RenameField(
            model_name='scoringleaderboard2016',
            old_name='extra_field_3',
            new_name='field_3',
        ),
    ]
