# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0015_auto_20161007_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='selector',
            field=models.CharField(default='-ret_field', max_length=50, null=True),
        ),
    ]
