# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0016_leaderboard_selector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringleaderboard2016',
            name='field_1',
        ),
        migrations.RemoveField(
            model_name='scoringleaderboard2016',
            name='field_2',
        ),
        migrations.RemoveField(
            model_name='scoringleaderboard2016',
            name='field_3',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='field_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='field_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='field_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='field',
            field=models.CharField(default='', max_length=50),
        ),
    ]
