# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0017_auto_20161007_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='field',
        ),
    ]
