# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 00:40
from __future__ import unicode_literals

import _operator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0018_remove_leaderboard_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='operator',
            field=models.CharField(choices=[('+', _operator.add), ('-', _operator.sub), ('*', _operator.mul), ('/', _operator.truediv)], default='+', max_length=10),
        ),
    ]
