# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard2', '0020_auto_20161007_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='operator',
            field=models.CharField(choices=[('+', '_operator.add'), ('-', '_operator.sub'), ('*', '_operator.mul'), ('/', '_operator.truediv'), ('greatest', 'django.db.models.functions.Greatest'), ('least', 'django.db.models.functions.Least')], default='+', max_length=10),
        ),
    ]
